### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by SudaYDD** [TensorThinker/QueryMatch#1]
Hi, 
I have downloaded the pretrained weights of Mask2former from this link (https://1drv.ms/u/c/e3df1503c007b3c7/EZcn4gxHhcZKjWRgZl9MbgoBS_TS-_EqnCvV355cSp4laQ?e=XQsvtM) and when trying to load the model, I get the following error: 

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory. 

Do you have any insight on what might be going on? 

I'm wondering if the mask2former_pretrained.pth file might be broken.

**Comment by SudaYDD** [comment]
My apologies, I realized it was my internet issue that caused the problem. When I downloaded again today, I found the issue resolved.

**Comment by sdnujianxing** [comment]
@SudaYDD 你好 复现成功了吗 你也是做visual grounding的吗 可以交流下吗

**Comment by SudaYDD** [comment]
> @SudaYDD 你好 复现成功了吗 你也是做visual grounding的吗 可以交流下吗

你好！我复现成功了。 我的方向是弱监督的visual grounding。gouchenyi0721@163.com这是我的邮箱

**Comment by sdnujianxing** [comment]
@SudaYDD  你好 消息我发您邮箱[gouchenyi0721@163.com]了

**Comment by Issac304** [comment]
(querymatch) ubuntu@ubuntu:~/16T/Tian/querymatch$ python -m pip install -e detectron2
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/ubuntu/16T/Tian/querymatch/detectron2
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ubuntu/16T/Tian/querymatch/detectron2/setup.py", line 11, in <module>
          from torch.utils.cpp_extension import CUDA_HOME, CppExtension, CUDAExtension
        File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
          from .hipify import hipify_python
        File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
        File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 1720, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.请教下这个怎么解决

**Comment by Issac304** [comment]
请教下
![image](https://github.com/user-attachments/assets/0df33444-0b70-4256-ab15-11e8f1b98977)
