### ISSUE TITLE
Detectron2安装失败

### ISSUE THREAD

**Issue by Issac304** [TensorThinker/QueryMatch#2]
(querymatch) ubuntu@ubuntu:~/16T/Tian/querymatch$ python -m pip install -e detectron2
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/ubuntu/16T/Tian/querymatch/detectron2
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [20 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/home/ubuntu/16T/Tian/querymatch/detectron2/setup.py", line 11, in
from torch.utils.cpp_extension import CUDA_HOME, CppExtension, CUDAExtension
File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 19, in
from .hipify import hipify_python
File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/site-packages/torch/utils/hipify/hipify_python.py", line 34, in
from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in
rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 415, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 493, in run
with Popen(*popenargs, **kwargs) as process:
File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 858, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "/home/ubuntu/.conda/envs/querymatch/lib/python3.8/subprocess.py", line 1720, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.请教下这个怎么解决

**Comment by Issac304** [comment]
解决了 gcc g++ torch版本问题
